const HomeProduct = [
  {
    id: 1,
    Name: "Product 1",
    price: 23,
    image: "images/p1.webp",
    cat: "tv",
    type: "new",
  },
  {
    id: 2,
    Name: "Product 2",
    price: 203,
    image: "images/p2.webp",
    cat: "laptop",
    type: "new",
  },
  {
    id: 3,
    Name: "Product 3",
    price: 35,
    image: "images/p3.webp",
    cat: "watch",
    type: "new",
  },
  {
    id: 4,
    Name: "Product 4",
    price: 210,
    image: "images/p4.webp",
    cat: "speaker",
    type: "new",
  },
  {
    id: 5,
    Name: "Product 5",
    price: 203,
    image: "images/p5.webp",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 6,
    Name: "Product 6",
    price: 88,
    image: "images/p6.webp",
    cat: "phone",
    type: "featured",
  },
  {
    id: 7,
    Name: "Product 7",
    price: 24,
    image: "images/p7.webp",
    cat: "electronics",
    type: "featured",
  },
  {
    id: 8,
    Name: "Product 8",
    price: 111,
    image: "images/p8.webp",
    cat: "speaker",
    type: "featured",
  },
  {
    id: 9,
    Name: "Product 9",
    price: 247,
    image: "images/p9.jpg",
    cat: "laptop",
    type: "top selling",
  },
  {
    id: 10,
    Name: "Product 10",
    price: 147,
    image: "images/p10.jpg",
    cat: "headphone",
    type: "top selling",
  },
  {
    id: 11,
    Name: "Product 11",
    price: 135,
    image: "images/p11.jpg",
    cat: "laptop",
    type: "top selling",
  },
  {
    id: 12,
    Name: "Product 12",
    price: 114,
    image: "images/p12.webp",
    cat: "tv",
    type: "top selling",
  },
];
export default HomeProduct;
